### ISSUE TITLE
Fix or remove the "Last Updated" functionality.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Support-Manual#22]
The "Last updated" functionality on the top of the page does not seem to be related to when a commit was pushed for the page in question and is misleading or not helpful. 

![screen shot 2018-07-06 at 7 24 21 am](https://user-images.githubusercontent.com/9629102/42376591-a8a39f70-80ed-11e8-94dd-b1a24924aabd.png)

If it only updates when we are updating directly on gitbook, we need to remove it, or create a workflow that makes it accurate.

**Comment by mathetos** [comment]
Pretty sure there's nothing we can do about that currently. The system doesn't give fine-grained control over items like that currently. The legacy version gave a lot more control -- the new version...less so. 

Closing for now, but let's keep it in mind as they build out their online docs more.
